### ISSUE TITLE
Out of memory issues (GPU)

### ISSUE THREAD

**Issue by d07RiV** [fchollet/keras#1587]
I'm training a model with Theano/CUDA, and if I attempt to specify a large batch_size (1024 in my case), it reports an out of memory error, which is understandable. However, if I change it back to a size that previously worked (I'm doing it in a notebook), it will still be out of memory, as if it didn't attempt to free whatever it allocated for the previous attempt, so I'm forced to restart the Python process (and reload all data/recompile models).

I can provide model code if needed, its on a laptop that does not have internet access currently.

**Comment by jocicmarko** [comment]
It sounds like a problem with IPython Notebook, maybe it doesn't release allocated resources (memory). It happened to me before.
I suggest you develop your model in a text editor or IDE, and run it through console.

**Comment by nouiz** [comment]
It is possible that cuda driver don't like this and stay in a bad state. It
isn't able to recover from all type of error. I'm not sure which one it
recover correctly and which one it don't.

Calling a_theano_function.free() could help free the memory, but as it was
said, running it outside ipython notebook would fix those problems.

**Comment by d07RiV** [comment]
If I run it as a complete python program then it obviously wouldn't be a problem because the exception would terminate the python process, but that defeats the purpose of being able to keep training the model and checking the results without having to recompile it every time.

I'm pretty sure running it in python shell would be the same as using the notebook, though.

It seems that it starts allocating large amounts of memory, but when it runs out it throws an exception and doesn't free the memory. I don't know if forcing garbage collection would help, but that theano free function should definitely help, thanks.

**Comment by moof2k** [comment]
Hitting this as well. I've been playing with a trivial model in jupyter and I've observed that while iterating in jupyter my GPU used memory (as reported by nvidia-settings) steadily increases in ~200mb increments until finally theano generates an out of memory error.

Calling ``del model``, ``gc.collect()`` seems to have no effect on used GPU memory. Restarting the jupyter kernel resolves it, but is undesirable.

**Comment by MannyKayy** [comment]
Has anyone managed to find a way around this (i.e. without restarting the kernel) ?

**Comment by slavivanov** [comment]
@MannyKayy deleting all IPython references to the model and calling the garbage collector works for me (using theano):
```
%xdel model
import gc
for i in range(3): gc.collect()
```

**Comment by Goddard** [comment]
having this issue myself with tensorflow, above^ method doesn't solve issue in notebook.

**Comment by lschaupp** [comment]
still no progress on this? I'm having the same issue...using tf and keras

**Comment by andyharless** [comment]
I have the same issue. Can't find any solution except to restart the notebook.

**Comment by m3h0w** [comment]
+1. Struggling with this a lot.

**Comment by JacoGasp** [comment]
Same for me. It would be great to not restart the notebook every time

**Comment by FMena14** [comment]
Same here. Any solution better than restart the kernel of the notebook?

**Comment by wangqin4377** [comment]
Why no one can solve this serious problem? My method is to shutdown the jupyter kernal everytime, too waste time.

**Comment by jackvial** [comment]
Having this problem too when training Matterport Mask RCNN. Restarting the Kernel fixes it.
