### ISSUE TITLE
error messages, import theano

### ISSUE THREAD

**Issue by ohnabe** [fchollet/keras#2900]
I updated keras to Keras 1.0.3 and theano with pip install  git+git://github.com/fchollet/keras.git --upgrade --no-deps and pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps. 

Ubuntu 14.04
Keras version 1.0.3
Theano version Theano-0.9.0.dev1

import theano
# output following error messages, 

In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:59:1: fatal error: cuda_runtime.h: No such file or directory
 #endif
 ^
compilation terminated.

['nvcc', '-shared', '-O3', '-use_fast_math', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/realnabe/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/cuda_ndarray', '-Xlinker', '-rpath,/usr/local/cuda-7.5/lib', '-Xlinker', '-rpath,/usr/local/cuda-7.5/lib64', '-I/home/realnabe/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda', '-I/home/realnabe/anaconda3/lib/python3.5/site-packages/numpy/core/include', '-I/home/realnabe/anaconda3/include/python3.5m', '-I/home/realnabe/anaconda3/lib/python3.5/site-packages/theano/gof', '-o', '/home/realnabe/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/home/realnabe/anaconda3/lib', '-lcublas', '-lpython3.5m', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -use_fast_math -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/realnabe/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/cuda_ndarray -Xlinker -rpath,/usr/local/cuda-7.5/lib -Xlinker -rpath,/usr/local/cuda-7.5/lib64 -I/home/realnabe/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda -I/home/realnabe/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/realnabe/anaconda3/include/python3.5m -I/home/realnabe/anaconda3/lib/python3.5/site-packages/theano/gof -o /home/realnabe/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/home/realnabe/anaconda3/lib -lcublas -lpython3.5m -lcudart')
# WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)

How can I fix it?

**Comment by ymcui** [comment]
it seems that your theano version is too high.
try theano v0.8.1?

**Comment by alyato** [comment]
My theano version is the 0.7.1,then i update it.

> sudo pip install --upgrade --no-deps theano

the theano is 0.8.2

**Comment by ohnabe** [comment]
Thanks, ymcui and alyno.

The same error messages appered when import keras.(theano=0.8.2 and keras=1.0.4)
But the error messages did not appear when import keras. (theano=0.82 and keras=0.3.1)

**Comment by MarinPri** [comment]
Hi,
had the same message when trying to install theano with gpu (geforce 1080, cuda 8.0) on Windows 10 with Visual Studio 2015.

Trying to understand the problem I realized, that the cuda sandbox is connected to cuDNN. Though cuCNN was installed (Version 5) it did not work. I simply forgot to add the installation path ob cuDNN to my system environment.
Done -> problem solved, the speed up is great:)

Regards, Martin

**Comment by wenxinxu** [comment]
Hi Marin,
Were you talking about theano/sandbox/cuda/? Could you please explain what you did with more details (like how it is connected with cuDNN and how to add cuDNN path to system)? I am facing with the same problem... Thanks a lot!

Best,Wenxin
