### ISSUE TITLE
fit_generator accumulates data on GPU?

### ISSUE THREAD

**Issue by shiretzet** [fchollet/keras#3553]
I use generators on my model using fit_generator.

After a few samples i get a GPU error that says i run out of memory.

Is it possible that the GPU stores the batches and accumulate data when using generators?

**Comment by carlthome** [comment]
No, that's not possible. While the generator is backed by a queue that stores samples, that's on CPU RAM.

Rather, VRAM usage will spike occasionally, so maintain some headroom. I like to see an average GPU memory use of 80%, and have the remaining 20% for spikes, just to play things safe.

Consider running `nvidia-smi dmon` in a terminal, when training your model, and look at the total memory usage.

**Comment by shiretzet** [comment]
Ok, problem solved.
My generator was making samples with different size for every batch. So once it was too big the GPU rised an error

**Comment by carlthome** [comment]
Good. Close this issue as it is resolved, please.
