### ISSUE TITLE
fit_generator converges slower and tensorboard's OOM problem

### ISSUE THREAD

**Issue by rabintang** [fchollet/keras#4797]
problem 1:
i changed my code from fit to fit_generator, however, i found it converged slower than using fit. Using fit it converges at 5th epoch, however, it doesn't converge even at 10th epoch when i change to fit_generator.
Moreover, when validation_data also uses fit_generator, the performance becomes much worse. Is my generator function has errors?

def batch_iter(x, y, batch_size):                                       
    """                                          
    Generates a batch iterator for a dataset.
    """                                                                 
    data_size = len(y)
    num_batches_per_epoch = int(len(y)/batch_size) if data_size%batch_size == 0 \
            else int(len(y)/batch_size) + 1              
    while 1:
        # Shuffle data
        shuffle_indices = np.random.permutation(np.arange(len(y)))
        x_shuffled = x[shuffle_indices]              
        y_shuffled = y[shuffle_indices]         
        # Shuffle the data at each epoch
        for batch_num in range(num_batches_per_epoch):
            start_index = batch_num * batch_size
            end_index = min((batch_num + 1) * batch_size, data_size)
            yield (x_shuffled[start_index:end_index],y_shuffled[start_index:end_index])

problem 2:
Added tensorboard callback, it always causes OOM (out of memory) problem, even i change to fit_generator. Seems, it will allocate a memory size as big as training data's.

Epoch 00000: val_acc improved from -inf to 0.12241, saving model to models/weights-best-label9-00-0.12.hdf5
Traceback (most recent call last):
  File "trainGraph.py", line 165, in <module>
    class_weight=class_weights)
  File "/home/tensorflow/.local/lib/python2.7/site-packages/keras/models.py", line 934, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/tensorflow/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1555, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/tensorflow/.local/lib/python2.7/site-packages/keras/callbacks.py", line 43, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/tensorflow/.local/lib/python2.7/site-packages/keras/callbacks.py", line 561, in on_epoch_end
    result = self.sess.run([self.merged], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[45551,2392,20]
	 [[Node: Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding_1_W/read, _recv_embedding_input_1_0/_119)]]
	 [[Node: cond/Merge/_123 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_31_cond/Merge", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by booble123** [comment]
Please take a look:

https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L551:

```
# TODO: implement batched calls to sess.run
# (current call will likely go OOM on GPU)
```

Also check out the rest of the code in that function.
Tensorboard callback passes validation data again through the network on epoch end and it doesn't use batches, so if your validation data is bigger than few samples it is very likely to cause OOM on GPU.

**Comment by ahundt** [comment]
I've noticed the GPU running out of memory when tensorboard is enabled as well. Is there a way to fix this with fewer downsides than #4834? i.e. reducing memory utilization with more consistency in the tensorboard charts

**Comment by Vladimir-Yashin** [comment]
@anundt: The only way I can think of is to split validation data into batches and then pass each batch through the model.

With this approach we're going to get a TensorBoard Summary object for each batch, so if you have, say, 1000 samples in validation_data and batch_size of 100 this would result in 10 Summaries and each summary object is going to be shown in TensorBoard Histogram and Distribution tabs separately.

I bet this is something nobody wants.

We could probably average across multiple Summary objects to form a single Summary object where all values are averages of corresponding values from batch-specific summaries, but this is a much more complex approach. There are no examples of doing it that way and generally Summary object is not supposed to be tampered with.

I checked few examples of code just to see how this problem is resolved and nobody aggregates statistics manually.
Tensorflow official example passes whole validation data through the model at once:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

It should be possible to pass something like "batch_size for TensorBoard" parameter that would be bigger than batch_size, so that you'd get more accurate stats, but it won't really resolve that problem that you need more GPU memory with TensorBoard enabled.

**Comment by ophiry** [comment]
Still an issue in keras2 and tf.contrib.keras

does the deeper integration in tf.contrib.keras make it easier to solve this? is there some kind of workaround?

**Comment by Vladimir-Yashin** [comment]
Current workaround is to disable  TensorBoard callback histograms.
If I remember correctly validation is done in batches everywhere except for TensorBoard.

**Comment by entelechie** [comment]
Is anyone going to fix the TensorBoard's batches compute?

**Comment by wgmg165** [comment]
I also get this error! when I traine the same model on a group of datasets, "ResourceExhaustedError: OOM when allocating tensor with shape", I can't fix it, please help me!
