### ISSUE TITLE
Use batch size in validation for limited GPU memory

### ISSUE THREAD

**Issue by calclavia** [fchollet/keras#6217]
Using Keras 2.0.0, Tensorflow 1.0.1.

I think this is more of a feature request, but it would be great if there's a way to specify/use batch size in `model.fit` during validation. Currently, it seems like the validation feeds in the entire validation set into the neural network, which, in my case, my GPU runs out of memory. Training works fine because batch size of 32 is small enough. A solution would be to chunk the validation into batches of 32 and validate them each individually, which will enable validation to run on large data sets on GPUs that have insufficient memory.

**Comment by fchollet** [comment]
In `model.fit`, the same batch size is used for training and for validation, which you specify via the `batch_size` keyword argument.

**Comment by calclavia** [comment]
@fchollet That's strange... My GPU trains the network fine, but when I enable 10% validation on data, it crashes (due to lack of memory) when it tries to validate the data at the end of the epoch. Changing validation split to 0 allows it to run fine.

Note: I have quite a large model architecture ~12 layers (6 of which are 128 unit LSTM layers) on Tesla K80.

Any possible suggestions on what might be wrong? Somehow validation requires more memory than training.

**Comment by fchollet** [comment]
Then you should simply decrease the batch size or decrease the network size.

**Comment by farizrahman4u** [comment]
But why would validation require more memory than training?

**Comment by calclavia** [comment]
@farizrahman4u Yes that's what I found to be strange. I tried this one two different GPUs, so it shouldn't be any fault with the specific hardware I'm using. If I manually try to call predict on given data, I'm able to do it without running out of memory. Only Keras validation causes this problem.

**Comment by fchollet** [comment]
There are various possible reasons. If you want to investigate this,
snapshot the TF graph before and after validation (using a custom callback
for instance).

**Comment by calclavia** [comment]
Would there be a way to specify a different batch size for model.fit during validation?

**Comment by waissbluth** [comment]
I am having this same issue. My model works just fine without validation but it runs out of GPU memory when validating, regardless of batch size. Could anybody figure out what is going on?

**Comment by divamgupta** [comment]
@fchollet I think there should be an option of different batch sizes for training and validation. In many cases we can't change the train batch_size as it effects the results. But the validation batch size can be changed. Even caffe supports that.

**Comment by rposer** [comment]
@calclavia Do you use `TensorBoard `callback?
I encountered the same problem, turned out it was (probably) caused by the `batch_size `argument of `TensorBoard `being too high.

**Comment by waissbluth** [comment]
@rposer I disabled TensorBoard stopped running out of memory on validation, with the same batch size. Thanks!

**Comment by getsanjeev** [comment]
@waissbluth @fchollet @divamgupta @calclavia 
I am facing the same issue, with deeplabv3+, with backbone = xception.  Only very small validation split works. Training goes fine, but runs into OOM error just when validation starts.
Has it been resolved?

**Comment by PowerOfCreation** [comment]
With validation data: https://pasteboard.co/IllA27U.png
Without validation data: https://pasteboard.co/IllBg7q.png
Code: https://gist.github.com/PowerOfCreation/b0940d377180d0131f51a538152f788b

Tested on single and multiple GPUs(Tesla K-20, K-80, V-100), same behavior on all systems. Strangely the memory usage is different on each system. K-20 requiring 8 GB of RAM, K-80 10 GB of RAM and V-100 requiring 36 GB of RAM, RAM usage spikes double when validation data is turned out.

Measurements have been made in steps all 10 seconds.

Tensorflow: 1.10
Keras: 2.1.6-tf
