### ISSUE TITLE
Can't run multiple processes of keras using each a different gpu, with CNTK backend

### ISSUE THREAD

**Issue by thdeltei** [fchollet/keras#7776]
I am trying to train the same model across my 4 GPUs with different hyperparameters.

I am setting these variables at the top of my scripts:

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="{}".format(GPU_ID)
os.environ["KERAS_BACKEND"] = "cntk"

The first script to run always respect its assigned GPU and start training on the GPU. The second and third and fourth scripts to be executed get these warnings:

```
keras\backend\cntk_backend.py:19: UserWarning: CNTK backend warning: GPU is not detected. CNTK's CPU version is not fully optimized,please run with GPU to get better performance.
  'CNTK backend warning: GPU is not detected. '
```

I am using the latest CNTK 2.1 version and keras, on a Windows machine.

**Comment by thdeltei** [comment]
Solved the problem by removing these lines:
```
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="{}".format(GPU_ID)
```
