### ISSUE TITLE
splitting data causes network to diverge

### ISSUE THREAD

**Issue by edocoh87** [fchollet/keras#900]
I'm training a net for a classification task.
I used the mnist_cnn.py as reference.
Currently I am limited to work with images of size 160x160 since using larger resolution causes the GPU to run out of memory (I have about 30K samples).
I tried to change the configuration to load images from an iterator in chunks of 5K (as suggested [here](https://github.com/fchollet/keras/issues/68)).
I am sure there is no bug in the iterator code.
I even ran some simple tests to see the affects of splitting the data and I saw longer convergence times when the data is split.
Is this normal behaviour? how can I overcome this problem?

**Comment by lemuriandezapada** [comment]
isn't the data loaded onto the gpu for every batch? I usually just fix this stuff by running smaller batches

**Comment by edocoh87** [comment]
The problem is with the limited amount of RAM. I don't know why I wrote the GPU runs out of memory..
I've made some progress in the issue. Currently I've saved the data as HDF5.
I just found out that using shuffle='batch' flag prevents the network from converging.
Didn't have time to figure out why yet.
Any ideas / known bugs?

**Comment by edocoh87** [comment]
It seems as if the problem is that the data is stored as chunks of the same label, so when shuffling in batch resolution this still produces a batch of the same label.
I'm not 100% sure yet as I need to store the huge amount of shuffled and see that it converges.
I'll update when I'm sure this is the issue.

**Comment by JordanPeltier** [comment]
@edocoh87 
I think I got the same problem. Did you find the solution?

**Comment by edocoh87** [comment]
Yes, the problem was that I stored the data ordered and therefore batches were homogenous (i.e. from the same class) and that of coarse prevents the network from converging.
